// London Underground Station Data
// All stations organised by line with official TfL colours
// Station counts verified against TfL official line pages
// Bakerloo: 25 | Central: 49 | Circle: 36 | District: 60 | H&C: 29
// Jubilee: 27 | Metropolitan: 34 | Northern: 50 | Piccadilly: 53 | Victoria: 16 | W&C: 2

export interface Station {
  id: string;
  name: string;
  zone?: string;
}

export interface Line {
  id: string;
  name: string;
  colour: string;      // Official TfL hex colour
  textColour: string;  // Text colour for contrast on line colour bg
  stations: Station[];
}

export const LINES: Line[] = [
  {
    id: "bakerloo",
    name: "Bakerloo",
    colour: "#894E24",
    textColour: "#FFFFFF",
    stations: [
      { id: "bak-01", name: "Harrow & Wealdstone", zone: "5" },
      { id: "bak-02", name: "Kenton", zone: "4" },
      { id: "bak-03", name: "South Kenton", zone: "4" },
      { id: "bak-04", name: "North Wembley", zone: "4" },
      { id: "bak-05", name: "Wembley Central", zone: "4" },
      { id: "bak-06", name: "Stonebridge Park", zone: "3" },
      { id: "bak-07", name: "Harlesden", zone: "3" },
      { id: "bak-08", name: "Willesden Junction", zone: "3" },
      { id: "bak-09", name: "Kensal Green", zone: "2" },
      { id: "bak-10", name: "Queen's Park", zone: "2" },
      { id: "bak-11", name: "Kilburn Park", zone: "2" },
      { id: "bak-12", name: "Maida Vale", zone: "2" },
      { id: "bak-13", name: "Warwick Avenue", zone: "2" },
      { id: "bak-14", name: "Paddington", zone: "1" },
      { id: "bak-15", name: "Edgware Road", zone: "1" },
      { id: "bak-16", name: "Marylebone", zone: "1" },
      { id: "bak-17", name: "Baker Street", zone: "1" },
      { id: "bak-18", name: "Regent's Park", zone: "1" },
      { id: "bak-19", name: "Oxford Circus", zone: "1" },
      { id: "bak-20", name: "Piccadilly Circus", zone: "1" },
      { id: "bak-21", name: "Charing Cross", zone: "1" },
      { id: "bak-22", name: "Embankment", zone: "1" },
      { id: "bak-23", name: "Waterloo", zone: "1" },
      { id: "bak-24", name: "Lambeth North", zone: "1" },
      { id: "bak-25", name: "Elephant & Castle", zone: "1/2" },
    ],
  },
  {
    id: "central",
    name: "Central",
    colour: "#E32017",
    textColour: "#FFFFFF",
    stations: [
      { id: "cen-01", name: "Epping", zone: "6" },
      { id: "cen-02", name: "Theydon Bois", zone: "6" },
      { id: "cen-03", name: "Debden", zone: "6" },
      { id: "cen-04", name: "Loughton", zone: "4" },
      { id: "cen-05", name: "Buckhurst Hill", zone: "5" },
      { id: "cen-06", name: "Woodford", zone: "4" },
      { id: "cen-07", name: "South Woodford", zone: "4" },
      { id: "cen-08", name: "Snaresbrook", zone: "4" },
      { id: "cen-09", name: "Wanstead", zone: "4" },
      { id: "cen-10", name: "Redbridge", zone: "4" },
      { id: "cen-11", name: "Gants Hill", zone: "4" },
      { id: "cen-12", name: "Newbury Park", zone: "4" },
      { id: "cen-13", name: "Barkingside", zone: "4" },
      { id: "cen-14", name: "Fairlop", zone: "4" },
      { id: "cen-15", name: "Hainault", zone: "4" },
      { id: "cen-16", name: "Grange Hill", zone: "4" },
      { id: "cen-17", name: "Chigwell", zone: "4" },
      { id: "cen-18", name: "Roding Valley", zone: "4" },
      { id: "cen-19", name: "Leytonstone", zone: "3/4" },
      { id: "cen-20", name: "Leyton", zone: "3" },
      { id: "cen-21", name: "Stratford", zone: "3" },
      { id: "cen-22", name: "Mile End", zone: "2" },
      { id: "cen-23", name: "Bethnal Green", zone: "2" },
      { id: "cen-24", name: "Liverpool Street", zone: "1" },
      { id: "cen-25", name: "Bank", zone: "1" },
      { id: "cen-26", name: "St. Paul's", zone: "1" },
      { id: "cen-27", name: "Chancery Lane", zone: "1" },
      { id: "cen-28", name: "Holborn", zone: "1" },
      { id: "cen-29", name: "Tottenham Court Road", zone: "1" },
      { id: "cen-30", name: "Oxford Circus", zone: "1" },
      { id: "cen-31", name: "Bond Street", zone: "1" },
      { id: "cen-32", name: "Marble Arch", zone: "1" },
      { id: "cen-33", name: "Lancaster Gate", zone: "1" },
      { id: "cen-34", name: "Queensway", zone: "1" },
      { id: "cen-35", name: "Notting Hill Gate", zone: "2" },
      { id: "cen-36", name: "Holland Park", zone: "2" },
      { id: "cen-37", name: "Shepherd's Bush", zone: "2" },
      { id: "cen-38", name: "White City", zone: "2" },
      { id: "cen-39", name: "East Acton", zone: "2" },
      { id: "cen-40", name: "North Acton", zone: "3" },
      { id: "cen-41", name: "West Acton", zone: "3" },
      { id: "cen-42", name: "Ealing Broadway", zone: "3" },
      { id: "cen-43", name: "Hanger Lane", zone: "3" },
      { id: "cen-44", name: "Perivale", zone: "4" },
      { id: "cen-45", name: "Greenford", zone: "4" },
      { id: "cen-46", name: "Northolt", zone: "5" },
      { id: "cen-47", name: "South Ruislip", zone: "5" },
      { id: "cen-48", name: "Ruislip Gardens", zone: "5" },
      { id: "cen-49", name: "West Ruislip", zone: "6" },
    ],
  },
  {
    id: "circle",
    name: "Circle",
    colour: "#FFD300",
    textColour: "#1C1C1E",
    stations: [
      { id: "cir-01", name: "Hammersmith", zone: "2" },
      { id: "cir-02", name: "Goldhawk Road", zone: "2" },
      { id: "cir-03", name: "Shepherd's Bush Market", zone: "2" },
      { id: "cir-04", name: "Wood Lane", zone: "2" },
      { id: "cir-05", name: "Latimer Road", zone: "2" },
      { id: "cir-06", name: "Ladbroke Grove", zone: "2" },
      { id: "cir-07", name: "Westbourne Park", zone: "2" },
      { id: "cir-08", name: "Royal Oak", zone: "2" },
      { id: "cir-09", name: "Paddington", zone: "1" },
      { id: "cir-10", name: "Edgware Road", zone: "1" },
      { id: "cir-11", name: "Baker Street", zone: "1" },
      { id: "cir-12", name: "Great Portland Street", zone: "1" },
      { id: "cir-13", name: "Euston Square", zone: "1" },
      { id: "cir-14", name: "King's Cross St. Pancras", zone: "1" },
      { id: "cir-15", name: "Farringdon", zone: "1" },
      { id: "cir-16", name: "Barbican", zone: "1" },
      { id: "cir-17", name: "Moorgate", zone: "1" },
      { id: "cir-18", name: "Liverpool Street", zone: "1" },
      { id: "cir-19", name: "Aldgate", zone: "1" },
      { id: "cir-20", name: "Tower Hill", zone: "1" },
      { id: "cir-21", name: "Monument", zone: "1" },
      { id: "cir-22", name: "Cannon Street", zone: "1" },
      { id: "cir-23", name: "Mansion House", zone: "1" },
      { id: "cir-24", name: "Blackfriars", zone: "1" },
      { id: "cir-25", name: "Temple", zone: "1" },
      { id: "cir-26", name: "Embankment", zone: "1" },
      { id: "cir-27", name: "Westminster", zone: "1" },
      { id: "cir-28", name: "St. James's Park", zone: "1" },
      { id: "cir-29", name: "Victoria", zone: "1" },
      { id: "cir-30", name: "Sloane Square", zone: "1" },
      { id: "cir-31", name: "South Kensington", zone: "1" },
      { id: "cir-32", name: "Gloucester Road", zone: "1" },
      { id: "cir-33", name: "High Street Kensington", zone: "1" },
      { id: "cir-34", name: "Notting Hill Gate", zone: "2" },
      { id: "cir-35", name: "Bayswater", zone: "1" },
      { id: "cir-36", name: "Paddington (H&C)", zone: "1" },
    ],
  },
  {
    id: "district",
    name: "District",
    colour: "#00782A",
    textColour: "#FFFFFF",
    stations: [
      { id: "dis-01", name: "Upminster", zone: "6" },
      { id: "dis-02", name: "Upminster Bridge", zone: "6" },
      { id: "dis-03", name: "Hornchurch", zone: "6" },
      { id: "dis-04", name: "Elm Park", zone: "6" },
      { id: "dis-05", name: "Dagenham East", zone: "5" },
      { id: "dis-06", name: "Dagenham Heathway", zone: "5" },
      { id: "dis-07", name: "Becontree", zone: "5" },
      { id: "dis-08", name: "Upney", zone: "4" },
      { id: "dis-09", name: "Barking", zone: "4" },
      { id: "dis-10", name: "East Ham", zone: "3/4" },
      { id: "dis-11", name: "Upton Park", zone: "3" },
      { id: "dis-12", name: "Plaistow", zone: "3" },
      { id: "dis-13", name: "West Ham", zone: "3" },
      { id: "dis-14", name: "Bromley-by-Bow", zone: "2/3" },
      { id: "dis-15", name: "Bow Road", zone: "2" },
      { id: "dis-16", name: "Mile End", zone: "2" },
      { id: "dis-17", name: "Stepney Green", zone: "2" },
      { id: "dis-18", name: "Whitechapel", zone: "2" },
      { id: "dis-19", name: "Aldgate East", zone: "1" },
      { id: "dis-20", name: "Tower Hill", zone: "1" },
      { id: "dis-21", name: "Monument", zone: "1" },
      { id: "dis-22", name: "Cannon Street", zone: "1" },
      { id: "dis-23", name: "Mansion House", zone: "1" },
      { id: "dis-24", name: "Blackfriars", zone: "1" },
      { id: "dis-25", name: "Temple", zone: "1" },
      { id: "dis-26", name: "Embankment", zone: "1" },
      { id: "dis-27", name: "Westminster", zone: "1" },
      { id: "dis-28", name: "St. James's Park", zone: "1" },
      { id: "dis-29", name: "Victoria", zone: "1" },
      { id: "dis-30", name: "Sloane Square", zone: "1" },
      { id: "dis-31", name: "South Kensington", zone: "1" },
      { id: "dis-32", name: "Gloucester Road", zone: "1" },
      { id: "dis-33", name: "Earl's Court", zone: "1/2" },
      { id: "dis-34", name: "West Brompton", zone: "2" },
      { id: "dis-35", name: "Fulham Broadway", zone: "2" },
      { id: "dis-36", name: "Parsons Green", zone: "2" },
      { id: "dis-37", name: "Putney Bridge", zone: "2" },
      { id: "dis-38", name: "East Putney", zone: "2" },
      { id: "dis-39", name: "Southfields", zone: "3" },
      { id: "dis-40", name: "Wimbledon Park", zone: "3" },
      { id: "dis-41", name: "Wimbledon", zone: "3" },
      { id: "dis-42", name: "Edgware Road", zone: "1" },
      { id: "dis-43", name: "Paddington", zone: "1" },
      { id: "dis-44", name: "Bayswater", zone: "1" },
      { id: "dis-45", name: "Notting Hill Gate", zone: "2" },
      { id: "dis-46", name: "High Street Kensington", zone: "1" },
      { id: "dis-47", name: "Kensington (Olympia)", zone: "2" },
      { id: "dis-48", name: "West Kensington", zone: "2" },
      { id: "dis-49", name: "Barons Court", zone: "2" },
      { id: "dis-50", name: "Hammersmith", zone: "2" },
      { id: "dis-51", name: "Ravenscourt Park", zone: "2" },
      { id: "dis-52", name: "Stamford Brook", zone: "2" },
      { id: "dis-53", name: "Turnham Green", zone: "3" },
      { id: "dis-54", name: "Chiswick Park", zone: "3" },
      { id: "dis-55", name: "Acton Town", zone: "3" },
      { id: "dis-56", name: "Ealing Common", zone: "3" },
      { id: "dis-57", name: "Ealing Broadway", zone: "3" },
      { id: "dis-58", name: "Gunnersbury", zone: "3" },
      { id: "dis-59", name: "Kew Gardens", zone: "3" },
      { id: "dis-60", name: "Richmond", zone: "4" },
    ],
  },
  {
    id: "hammersmith-city",
    name: "Hammersmith & City",
    colour: "#F3A9BB",
    textColour: "#1C1C1E",
    stations: [
      { id: "hac-01", name: "Hammersmith", zone: "2" },
      { id: "hac-02", name: "Goldhawk Road", zone: "2" },
      { id: "hac-03", name: "Shepherd's Bush Market", zone: "2" },
      { id: "hac-04", name: "Wood Lane", zone: "2" },
      { id: "hac-05", name: "Latimer Road", zone: "2" },
      { id: "hac-06", name: "Ladbroke Grove", zone: "2" },
      { id: "hac-07", name: "Westbourne Park", zone: "2" },
      { id: "hac-08", name: "Royal Oak", zone: "2" },
      { id: "hac-09", name: "Paddington", zone: "1" },
      { id: "hac-10", name: "Edgware Road", zone: "1" },
      { id: "hac-11", name: "Baker Street", zone: "1" },
      { id: "hac-12", name: "Great Portland Street", zone: "1" },
      { id: "hac-13", name: "Euston Square", zone: "1" },
      { id: "hac-14", name: "King's Cross St. Pancras", zone: "1" },
      { id: "hac-15", name: "Farringdon", zone: "1" },
      { id: "hac-16", name: "Barbican", zone: "1" },
      { id: "hac-17", name: "Moorgate", zone: "1" },
      { id: "hac-18", name: "Liverpool Street", zone: "1" },
      { id: "hac-19", name: "Aldgate East", zone: "1" },
      { id: "hac-20", name: "Whitechapel", zone: "2" },
      { id: "hac-21", name: "Stepney Green", zone: "2" },
      { id: "hac-22", name: "Mile End", zone: "2" },
      { id: "hac-23", name: "Bow Road", zone: "2" },
      { id: "hac-24", name: "Bromley-by-Bow", zone: "2/3" },
      { id: "hac-25", name: "West Ham", zone: "3" },
      { id: "hac-26", name: "Plaistow", zone: "3" },
      { id: "hac-27", name: "Upton Park", zone: "3" },
      { id: "hac-28", name: "East Ham", zone: "3/4" },
      { id: "hac-29", name: "Barking", zone: "4" },
    ],
  },
  {
    id: "jubilee",
    name: "Jubilee",
    colour: "#A0A5A9",
    textColour: "#1C1C1E",
    stations: [
      { id: "jub-01", name: "Stanmore", zone: "5" },
      { id: "jub-02", name: "Canons Park", zone: "5" },
      { id: "jub-03", name: "Queensbury", zone: "4" },
      { id: "jub-04", name: "Kingsbury", zone: "4" },
      { id: "jub-05", name: "Wembley Park", zone: "4" },
      { id: "jub-06", name: "Neasden", zone: "3" },
      { id: "jub-07", name: "Dollis Hill", zone: "3" },
      { id: "jub-08", name: "Willesden Green", zone: "2/3" },
      { id: "jub-09", name: "Kilburn", zone: "2" },
      { id: "jub-10", name: "West Hampstead", zone: "2" },
      { id: "jub-11", name: "Finchley Road", zone: "2" },
      { id: "jub-12", name: "Swiss Cottage", zone: "2" },
      { id: "jub-13", name: "St. John's Wood", zone: "2" },
      { id: "jub-14", name: "Baker Street", zone: "1" },
      { id: "jub-15", name: "Bond Street", zone: "1" },
      { id: "jub-16", name: "Green Park", zone: "1" },
      { id: "jub-17", name: "Westminster", zone: "1" },
      { id: "jub-18", name: "Waterloo", zone: "1" },
      { id: "jub-19", name: "Southwark", zone: "1" },
      { id: "jub-20", name: "London Bridge", zone: "1" },
      { id: "jub-21", name: "Bermondsey", zone: "2" },
      { id: "jub-22", name: "Canada Water", zone: "2" },
      { id: "jub-23", name: "Canary Wharf", zone: "2" },
      { id: "jub-24", name: "North Greenwich", zone: "3" },
      { id: "jub-25", name: "Canning Town", zone: "3" },
      { id: "jub-26", name: "West Ham", zone: "3" },
      { id: "jub-27", name: "Stratford", zone: "3" },
    ],
  },
  {
    id: "metropolitan",
    name: "Metropolitan",
    colour: "#9B0056",
    textColour: "#FFFFFF",
    stations: [
      { id: "met-01", name: "Aldgate", zone: "1" },
      { id: "met-02", name: "Liverpool Street", zone: "1" },
      { id: "met-03", name: "Moorgate", zone: "1" },
      { id: "met-04", name: "Barbican", zone: "1" },
      { id: "met-05", name: "Farringdon", zone: "1" },
      { id: "met-06", name: "King's Cross St. Pancras", zone: "1" },
      { id: "met-07", name: "Euston Square", zone: "1" },
      { id: "met-08", name: "Great Portland Street", zone: "1" },
      { id: "met-09", name: "Baker Street", zone: "1" },
      { id: "met-10", name: "Finchley Road", zone: "2" },
      { id: "met-11", name: "Wembley Park", zone: "4" },
      { id: "met-12", name: "Preston Road", zone: "4" },
      { id: "met-13", name: "Northwick Park", zone: "5" },
      { id: "met-14", name: "Harrow-on-the-Hill", zone: "5" },
      { id: "met-15", name: "North Harrow", zone: "5" },
      { id: "met-16", name: "Pinner", zone: "5" },
      { id: "met-17", name: "Northwood Hills", zone: "6" },
      { id: "met-18", name: "Northwood", zone: "6" },
      { id: "met-19", name: "Moor Park", zone: "6" },
      { id: "met-20", name: "Croxley Green", zone: "7" },
      { id: "met-21", name: "Watford", zone: "7" },
      { id: "met-22", name: "Rickmansworth", zone: "7" },
      { id: "met-23", name: "Chorleywood", zone: "7" },
      { id: "met-24", name: "Chalfont & Latimer", zone: "8" },
      { id: "met-25", name: "Chesham", zone: "9" },
      { id: "met-26", name: "Amersham", zone: "9" },
      { id: "met-27", name: "West Harrow", zone: "5" },
      { id: "met-28", name: "Eastcote", zone: "5" },
      { id: "met-29", name: "Ruislip Manor", zone: "6" },
      { id: "met-30", name: "Ruislip", zone: "6" },
      { id: "met-31", name: "Ickenham", zone: "6" },
      { id: "met-32", name: "Hillingdon", zone: "6" },
      { id: "met-33", name: "Uxbridge", zone: "6" },
      { id: "met-34", name: "Rayners Lane", zone: "5" },
    ],
  },
  {
    id: "northern",
    name: "Northern",
    colour: "#000000",
    textColour: "#FFFFFF",
    stations: [
      { id: "nor-01", name: "Edgware", zone: "5" },
      { id: "nor-02", name: "Burnt Oak", zone: "4" },
      { id: "nor-03", name: "Colindale", zone: "4" },
      { id: "nor-04", name: "Hendon Central", zone: "3" },
      { id: "nor-05", name: "Brent Cross", zone: "3" },
      { id: "nor-06", name: "Golders Green", zone: "3" },
      { id: "nor-07", name: "Hampstead", zone: "2" },
      { id: "nor-08", name: "Belsize Park", zone: "2" },
      { id: "nor-09", name: "Chalk Farm", zone: "2" },
      { id: "nor-10", name: "Mill Hill East", zone: "4" },
      { id: "nor-11", name: "Finchley Central", zone: "4" },
      { id: "nor-12", name: "East Finchley", zone: "3" },
      { id: "nor-13", name: "Highgate", zone: "3" },
      { id: "nor-14", name: "Archway", zone: "2/3" },
      { id: "nor-15", name: "Tufnell Park", zone: "2" },
      { id: "nor-16", name: "Kentish Town", zone: "2" },
      { id: "nor-17", name: "High Barnet", zone: "5" },
      { id: "nor-18", name: "Totteridge & Whetstone", zone: "4" },
      { id: "nor-19", name: "Woodside Park", zone: "4" },
      { id: "nor-20", name: "West Finchley", zone: "4" },
      { id: "nor-21", name: "Camden Town", zone: "2" },
      { id: "nor-22", name: "Mornington Crescent", zone: "2" },
      { id: "nor-23", name: "Euston", zone: "1" },
      { id: "nor-24", name: "Warren Street", zone: "1" },
      { id: "nor-25", name: "Goodge Street", zone: "1" },
      { id: "nor-26", name: "Tottenham Court Road", zone: "1" },
      { id: "nor-27", name: "Leicester Square", zone: "1" },
      { id: "nor-28", name: "Charing Cross", zone: "1" },
      { id: "nor-29", name: "Embankment", zone: "1" },
      { id: "nor-30", name: "Waterloo", zone: "1" },
      { id: "nor-31", name: "Nine Elms", zone: "1" },
      { id: "nor-32", name: "Battersea Power Station", zone: "1" },
      { id: "nor-33", name: "King's Cross St. Pancras", zone: "1" },
      { id: "nor-34", name: "Angel", zone: "1" },
      { id: "nor-35", name: "Old Street", zone: "1" },
      { id: "nor-36", name: "Moorgate", zone: "1" },
      { id: "nor-37", name: "Bank", zone: "1" },
      { id: "nor-38", name: "London Bridge", zone: "1" },
      { id: "nor-39", name: "Borough", zone: "1" },
      { id: "nor-40", name: "Elephant & Castle", zone: "1/2" },
      { id: "nor-41", name: "Kennington", zone: "1/2" },
      { id: "nor-42", name: "Oval", zone: "2" },
      { id: "nor-43", name: "Stockwell", zone: "2" },
      { id: "nor-44", name: "Clapham North", zone: "2" },
      { id: "nor-45", name: "Clapham Common", zone: "2" },
      { id: "nor-46", name: "Clapham South", zone: "2" },
      { id: "nor-47", name: "Balham", zone: "3" },
      { id: "nor-48", name: "Tooting Bec", zone: "3" },
      { id: "nor-49", name: "Tooting Broadway", zone: "3" },
      { id: "nor-50", name: "Colliers Wood", zone: "3" },
      { id: "nor-51", name: "South Wimbledon", zone: "4" },
      { id: "nor-52", name: "Morden", zone: "4" },
    ],
  },
  {
    id: "piccadilly",
    name: "Piccadilly",
    colour: "#003688",
    textColour: "#FFFFFF",
    stations: [
      { id: "pic-01", name: "Cockfosters", zone: "5" },
      { id: "pic-02", name: "Oakwood", zone: "5" },
      { id: "pic-03", name: "Southgate", zone: "4" },
      { id: "pic-04", name: "Arnos Grove", zone: "4" },
      { id: "pic-05", name: "Bounds Green", zone: "3/4" },
      { id: "pic-06", name: "Wood Green", zone: "3" },
      { id: "pic-07", name: "Turnpike Lane", zone: "3" },
      { id: "pic-08", name: "Manor House", zone: "2/3" },
      { id: "pic-09", name: "Finsbury Park", zone: "2" },
      { id: "pic-10", name: "Arsenal", zone: "2" },
      { id: "pic-11", name: "Holloway Road", zone: "2" },
      { id: "pic-12", name: "Caledonian Road", zone: "2" },
      { id: "pic-13", name: "King's Cross St. Pancras", zone: "1" },
      { id: "pic-14", name: "Russell Square", zone: "1" },
      { id: "pic-15", name: "Holborn", zone: "1" },
      { id: "pic-16", name: "Covent Garden", zone: "1" },
      { id: "pic-17", name: "Leicester Square", zone: "1" },
      { id: "pic-18", name: "Piccadilly Circus", zone: "1" },
      { id: "pic-19", name: "Green Park", zone: "1" },
      { id: "pic-20", name: "Hyde Park Corner", zone: "1" },
      { id: "pic-21", name: "Knightsbridge", zone: "1" },
      { id: "pic-22", name: "South Kensington", zone: "1" },
      { id: "pic-23", name: "Gloucester Road", zone: "1" },
      { id: "pic-24", name: "Earl's Court", zone: "1/2" },
      { id: "pic-25", name: "Barons Court", zone: "2" },
      { id: "pic-26", name: "Hammersmith", zone: "2" },
      { id: "pic-27", name: "Ravenscourt Park", zone: "2" },
      { id: "pic-28", name: "Stamford Brook", zone: "2" },
      { id: "pic-29", name: "Turnham Green", zone: "3" },
      { id: "pic-30", name: "Gunnersbury", zone: "3" },
      { id: "pic-31", name: "Kew Gardens", zone: "3" },
      { id: "pic-32", name: "Richmond", zone: "4" },
      { id: "pic-33", name: "Acton Town", zone: "3" },
      { id: "pic-34", name: "Ealing Common", zone: "3" },
      { id: "pic-35", name: "North Ealing", zone: "3" },
      { id: "pic-36", name: "Park Royal", zone: "3" },
      { id: "pic-37", name: "Alperton", zone: "4" },
      { id: "pic-38", name: "Sudbury Town", zone: "4" },
      { id: "pic-39", name: "Sudbury Hill", zone: "4" },
      { id: "pic-40", name: "South Harrow", zone: "5" },
      { id: "pic-41", name: "Rayners Lane", zone: "5" },
      { id: "pic-42", name: "Eastcote", zone: "5" },
      { id: "pic-43", name: "Ruislip Manor", zone: "6" },
      { id: "pic-44", name: "Ruislip", zone: "6" },
      { id: "pic-45", name: "Ickenham", zone: "6" },
      { id: "pic-46", name: "Hillingdon", zone: "6" },
      { id: "pic-47", name: "Uxbridge", zone: "6" },
      { id: "pic-48", name: "South Ealing", zone: "3" },
      { id: "pic-49", name: "Northfields", zone: "3" },
      { id: "pic-50", name: "Boston Manor", zone: "4" },
      { id: "pic-51", name: "Osterley", zone: "4" },
      { id: "pic-52", name: "Hounslow East", zone: "4" },
      { id: "pic-53", name: "Hounslow Central", zone: "4" },
      { id: "pic-54", name: "Hounslow West", zone: "5" },
      { id: "pic-55", name: "Hatton Cross", zone: "5/6" },
      { id: "pic-56", name: "Heathrow Terminals 2 & 3", zone: "6" },
      { id: "pic-57", name: "Heathrow Terminal 4", zone: "6" },
      { id: "pic-58", name: "Heathrow Terminal 5", zone: "6" },
    ],
  },
  {
    id: "victoria",
    name: "Victoria",
    colour: "#0098D4",
    textColour: "#FFFFFF",
    stations: [
      { id: "vic-01", name: "Brixton", zone: "2" },
      { id: "vic-02", name: "Stockwell", zone: "2" },
      { id: "vic-03", name: "Vauxhall", zone: "1/2" },
      { id: "vic-04", name: "Pimlico", zone: "1" },
      { id: "vic-05", name: "Victoria", zone: "1" },
      { id: "vic-06", name: "Green Park", zone: "1" },
      { id: "vic-07", name: "Oxford Circus", zone: "1" },
      { id: "vic-08", name: "Warren Street", zone: "1" },
      { id: "vic-09", name: "Euston", zone: "1" },
      { id: "vic-10", name: "King's Cross St. Pancras", zone: "1" },
      { id: "vic-11", name: "Highbury & Islington", zone: "2" },
      { id: "vic-12", name: "Finsbury Park", zone: "2" },
      { id: "vic-13", name: "Seven Sisters", zone: "3" },
      { id: "vic-14", name: "Tottenham Hale", zone: "3" },
      { id: "vic-15", name: "Blackhorse Road", zone: "3" },
      { id: "vic-16", name: "Walthamstow Central", zone: "3" },
    ],
  },
  {
    id: "waterloo-city",
    name: "Waterloo & City",
    colour: "#95CDBA",
    textColour: "#1C1C1E",
    stations: [
      { id: "wac-01", name: "Waterloo", zone: "1" },
      { id: "wac-02", name: "Bank", zone: "1" },
    ],
  },
];

export const TOTAL_STATIONS = LINES.reduce((sum, line) => sum + line.stations.length, 0);
